[myoktros]
gestures =
    REST
    GRAB
    STRETCH_FINGERS
    EXTENSION
    HORN
    FLEMING
# THUMBS_UP
# FLEXION
# TENNET
# SHOOT

[myoktros.trigger_map]
confirm = STRETCH_FINGERS
delete = EXTENSION
grabbed = GRAB
play = HORN

[myoktros.robot]
driver = xarm_rosws

[myoktros.robot.xarm_rosws]
model = lite6
ip = 127.0.0.1
port = 8765
