[myoktros]
gestures =
    REST
    GRAB
    PUSH
    EXTENSION
    FLEXION
    RAKE
    HORN
    FLEMING
    THUMBS_UP
    SHOOT
    TENNET

[myoktros.trigger_map]
confirm = FLEXION
grabbed = GRAB
play = FLEMING

[myoktros.robot]
driver = xarm_rosws
#driver = darwin

[myoktros.robot.xarm_rosws]
model = lite6
ip = 127.0.0.1
port = 8765
