version: "3.9"
networks:
  ros:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24
services:
  ros2-xarm:
    image: ghcr.io/iomz/ros2-xarm:humble
    container_name: ros2-xarm
    restart: unless-stopped
    command: ros2 launch xarm_api lite6_driver.launch.py robot_ip:="${ROBOT_IP}"
    #command: ros2 launch xarm_api xarm7_driver.launch.py robot_ip:="${ROBOT_IP}"
    networks:
      ros:
        ipv4_address: 10.77.77.77
  xarm-rosws:
    build: ./src/xarm_rosws
    container_name: xarm-rosws
    depends_on:
      - ros2-xarm
    ports:
      - 8765:8765/tcp
    networks:
      ros:
        ipv4_address: 10.77.77.2
