version: "3.9"
services:
  ros2-xarm:
    image: ghcr.io/iomz/ros2-xarm:humble
    container_name: ros2-xarm
    restart: unless-stopped
    command: ros2 launch xarm_api lite6_driver.launch.py robot_ip:="${ROBOT_IP}"
