name: build
on:
  pull_request:
  release:
    types: [published]
jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: chartboost/ruff-action@v1
      - name: Build
        run: |
          pip install hatch
          python -m hatch build
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
